<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="component" nsURI="http://dlut.mbsa/component" nsPrefix="component_">
  <eClassifiers xsi:type="ecore:EClass" name="ComponentElement" abstract="true" eSuperTypes="http://dlut.mbsa/base#//ArtifactElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPackage" eSuperTypes="#//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ComponentElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
        eType="#//ComponentPackageInterface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPackageInterface" eSuperTypes="#//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" lowerBound="1"
        eType="#//ComponentPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPackageBinding" eSuperTypes="#//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participantPackage" lowerBound="2"
        upperBound="-1" eType="#//ComponentPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reuse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cots" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="safety_related" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sil" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="componentType" lowerBound="1"
        eType="#//ComponentType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//Input" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//Output" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sub_components" upperBound="-1"
        eType="#//ComponentElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="failure_modes" upperBound="-1"
        eType="#//FailureMode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="safety_mechanisms" upperBound="-1"
        eType="#//SafetyMechanism" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" upperBound="-1"
        eType="ecore:EClass http://dlut.mbsa/base#//ArtifactElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentRelationship" eSuperTypes="#//ComponentElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentAsset" abstract="true" eSuperTypes="#//ComponentElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Function" eSuperTypes="#//ComponentAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="func" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//ComponentAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//ComponentAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="output" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentSafetyElement" abstract="true"
      eSuperTypes="#//ComponentAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="identity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FailureSeverity">
    <eLiterals name="catastrophic" value="1"/>
    <eLiterals name="fatal" value="2"/>
    <eLiterals name="moderate" value="3"/>
    <eLiterals name="minor" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentType">
    <eLiterals name="function" value="1"/>
    <eLiterals name="hardware" value="2"/>
    <eLiterals name="software" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ToleranceType">
    <eLiterals name="oneoo1" value="1"/>
    <eLiterals name="oneoo2" value="2"/>
    <eLiterals name="oneoo3" value="3"/>
    <eLiterals name="twooo3" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailureMode" eSuperTypes="#//ComponentSafetyElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cause" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="safety_related" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazards" upperBound="-1"
        eType="ecore:EClass http://dlut.mbsa/base#//ArtifactElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regional" eType="#//RegionalEffect"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="higher_level" eType="#//HigherLevelEffect"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="final" eType="#//FinalEffect"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SafetyMechanism" eSuperTypes="#//ComponentSafetyElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="handle" eType="#//FailureMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="coverage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FailureEffect" abstract="true" eSuperTypes="#//ComponentSafetyElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affected" upperBound="-1"
        eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegionalEffect" eSuperTypes="#//FailureEffect"/>
  <eClassifiers xsi:type="ecore:EClass" name="HigherLevelEffect" eSuperTypes="#//FailureEffect"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalEffect" eSuperTypes="#//FailureEffect"/>
</ecore:EPackage>
