<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mbsa" nsURI="http://dlut.mbsa/mbsa" nsPrefix="mbsa_">
  <eClassifiers xsi:type="ecore:EClass" name="MBSAPackage" eSuperTypes="http://dlut.mbsa/base#//ArtifactElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mbsaPackages" upperBound="-1"
        eType="#//MBSAPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentPackage" upperBound="-1"
        eType="ecore:EClass http://dlut.mbsa/component#//ComponentPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirementPackage" upperBound="-1"
        eType="ecore:EClass http://dlut.mbsa/requirement#//RequirementPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hazardPackage" upperBound="-1"
        eType="ecore:EClass http://dlut.mbsa/hazard#//HazardPackage" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
